SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS CURSAN;
DROP TABLE IF EXISTS HACEN;
DROP TABLE IF EXISTS REALIZAN;
DROP TABLE IF EXISTS ALUMNOS;
DROP TABLE IF EXISTS IMPARTEN;
DROP TABLE IF EXISTS ASIGNATURAS;
DROP TABLE IF EXISTS ELABORAN;
DROP TABLE IF EXISTS EXAMENES;
DROP TABLE IF EXISTS PRACTICAS;
DROP TABLE IF EXISTS PROFESORES;




/* Create Tables */

CREATE TABLE ALUMNOS
(
	NUM_ALU int NOT NULL AUTO_INCREMENT,
	NOMBRE varchar(150),
	GRUPO varchar(150),
	PRIMARY KEY (NUM_ALU),
	UNIQUE (NUM_ALU)
);


CREATE TABLE ASIGNATURAS
(
	NUM_ASI int NOT NULL AUTO_INCREMENT,
	NOMBRE varchar(150),
	PRIMARY KEY (NUM_ASI),
	UNIQUE (NUM_ASI)
);


CREATE TABLE CURSAN
(
	NUM_ALU int NOT NULL,
	NUM_ASI int NOT NULL,
	TRIMESTRE int,
	UNIQUE (NUM_ALU),
	UNIQUE (NUM_ASI)
);


CREATE TABLE ELABORAN
(
	COD_PRACTICA int NOT NULL,
	NUM_PROF int NOT NULL,
	FECHA date,
	UNIQUE (COD_PRACTICA),
	UNIQUE (NUM_PROF)
);


CREATE TABLE EXAMENES
(
	NUM_EXAMEN int NOT NULL AUTO_INCREMENT,
	NUM_PREGUNTAS int,
	FECHA date,
	PRIMARY KEY (NUM_EXAMEN),
	UNIQUE (NUM_EXAMEN)
);


CREATE TABLE HACEN
(
	NUM_ALU int NOT NULL,
	NUM_EXAMEN int NOT NULL,
	NOTA varchar(150),
	UNIQUE (NUM_ALU),
	UNIQUE (NUM_EXAMEN)
);


CREATE TABLE IMPARTEN
(
	NUM_ASI int NOT NULL,
	NUM_PROF int NOT NULL,
	UNIQUE (NUM_ASI),
	UNIQUE (NUM_PROF)
);


CREATE TABLE PRACTICAS
(
	COD_PRACTICA int NOT NULL AUTO_INCREMENT,
	TITULO varchar(150),
	NIVEL varchar(150),
	PRIMARY KEY (COD_PRACTICA),
	UNIQUE (COD_PRACTICA)
);


CREATE TABLE PROFESORES
(
	NUM_PROF int NOT NULL AUTO_INCREMENT,
	NOMBRE varchar(150),
	PRIMARY KEY (NUM_PROF),
	UNIQUE (NUM_PROF)
);


CREATE TABLE REALIZAN
(
	NUM_ALU int NOT NULL,
	COD_PRACTICA int NOT NULL,
	FECHA date,
	NOTA varchar(150),
	UNIQUE (NUM_ALU),
	UNIQUE (COD_PRACTICA)
);



/* Create Foreign Keys */

ALTER TABLE CURSAN
	ADD FOREIGN KEY (NUM_ALU)
	REFERENCES ALUMNOS (NUM_ALU)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HACEN
	ADD FOREIGN KEY (NUM_ALU)
	REFERENCES ALUMNOS (NUM_ALU)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE REALIZAN
	ADD FOREIGN KEY (NUM_ALU)
	REFERENCES ALUMNOS (NUM_ALU)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CURSAN
	ADD FOREIGN KEY (NUM_ASI)
	REFERENCES ASIGNATURAS (NUM_ASI)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE IMPARTEN
	ADD FOREIGN KEY (NUM_ASI)
	REFERENCES ASIGNATURAS (NUM_ASI)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HACEN
	ADD FOREIGN KEY (NUM_EXAMEN)
	REFERENCES EXAMENES (NUM_EXAMEN)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ELABORAN
	ADD FOREIGN KEY (COD_PRACTICA)
	REFERENCES PRACTICAS (COD_PRACTICA)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE REALIZAN
	ADD FOREIGN KEY (COD_PRACTICA)
	REFERENCES PRACTICAS (COD_PRACTICA)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ELABORAN
	ADD FOREIGN KEY (NUM_PROF)
	REFERENCES PROFESORES (NUM_PROF)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE IMPARTEN
	ADD FOREIGN KEY (NUM_PROF)
	REFERENCES PROFESORES (NUM_PROF)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



